### ISSUE TITLE
umi3 报错

### ISSUE THREAD

**Issue by ghost** [xusanduo08/umi-plugin-upload#4]
![image](https://user-images.githubusercontent.com/15773714/82746113-c1439400-9dbe-11ea-9ab7-9508bbb896dd.png)

**Comment by xusanduo08** [comment]
@kokiy umi3.x请使用[umi-plugin-upload](https://www.npmjs.com/package/umi-plugin-upload-new)

**Comment by ghost** [comment]
棒棒的
